1.6产品手册更新
cocos-creator/docs-ice pull request #63
Opened 2022-04-21 07:35 UTC by qbl0724

2.裁剪音频、视频.       ✅

3.图片、形状、音频的阴影，填充，边框属性更新；图片新增按形状裁剪 ✅

4.动效新增；✅

5.事件新增：播放音频；✅

6.双击形状，可以在形状内部添加文字；✅

7.spine动画的动作可以在列表内显示；✅

8.上传、导入功能优化 ✅

9.组合对象 ✅

2022-04-21 07:49 UTC, WisteriaCyan commented on zh/effect/index.md
> +    - 目前支持有四类动作动效，分别是出现、消失、强调和路径动效，为对象选择合适的动作动效，便可在课件中实现趣味的动效效果。
```suggestion
目前支持有四类动作动效，分别是出现、消失、强调和路径动效，为对象选择合适的动作动效，便可在课件中实现趣味的动效效果。
```

2022-04-21 07:59 UTC, WisteriaCyan commented on zh/resource/index.md
> +> **注意**：上传课程时，不会上传课程中使用的本地图片到素材库，支持定制限制上传权限。
```suggestion
> **注意**：上传课程时，不会上传课程中使用的本地图片到素材库。
```

2022-04-21 08:03 UTC, WisteriaCyan commented on zh/tools/object/audio/index.md
> +![替换音频](img/changeaudio.png)
图片链接前需要加缩进，以下都要~

2022-04-21 08:04 UTC, WisteriaCyan commented on zh/tools/object/image/index.md
> +![图片裁剪](img/imagecut.png)
图片链接需要缩进，以下都是~

2022-04-21 08:05 UTC, WisteriaCyan commented on zh/tools/object/index.md
> +Windows 系统按住 Ctrl 键，MacOS 系统按住 Command 键，可以在对象列表内，进行多选对象的操作。对象多选完成后，右击鼠标，会打开操作面板，点击 **新建组合**，可以对多选的对象进行组合。
建议分3点：新建组合、编辑组合、取消组合

2022-04-21 08:05 UTC, WisteriaCyan commented on zh/tools/object/shape/index.md
> +![形状边框](img/shapeframe.png)
图片链接需要缩进

2022-04-21 08:10 UTC, WisteriaCyan commented on zh/tools/object/audio/index.md
> +音频边框：可以对音频的边框属性进行相应设置。支持设置边框颜色以及边框粗细。
这个需要分小点，且需要缩进~

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse requested changes

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/tools/object/video/index.md
>      >**注意**：一些移动端的浏览器或 WebView 不允许自动播放视频，即使设置了自动播放，也需要用户手动播放视频。
```suggestion
    > **注意**：一些移动端的浏览器或 WebView 不允许自动播放视频，即使设置了自动播放，也需要用户手动播放视频。
```

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/effect/index.md
> +> **注意**：下拉框里显示的 **动作** 是根据选中的**Spine** 或者 **DragonBones** 对象决定的，下拉框内只会显示当前选中的**Spine** 或者 **DragonBones**对象带有的动作。
```suggestion
> **注意**：下拉框里显示的 **动作** 是根据选中的 **Spine** 或者 **DragonBones** 对象决定的，下拉框内只会显示当前选中的 **Spine** 或者 **DragonBones** 对象带有的动作。
```

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/effect/index.md
> +![基本属性](img/basicattribute.png)
```suggestion
    ![基本属性](img/basicattribute.png)
```

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/effect/index.md
> +![触发器](img/trigger.png)
```suggestion
    ![触发器](img/trigger.png)
```

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/effect/index.md
> +- **出现动效**：目前支持弹跳、淡入、翻转、浮入、飞入以及缩放动效。用于设置对象的在编辑器的出现效果。
[可选]一个小建议，说明的顺序和名称建议和界面菜单一致，可以让新手读起来更顺畅。

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/tools/object/video/index.md
> +选中视频对象，可以在右侧属性面板编辑 **视频文件**、**裁剪视频**、**视频播放设置**、**视频封面**、**视频播放器皮肤**、**视频不透明度**。
中文句子内部的并列词，最后一个尽量使用（和）来连接，使句子读起来更加连贯

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/tools/object/animation/index.md
> +动画目前支持本地或素材库插入 Spine、DragonBones、粒子、GIF、序列帧动画。
中文句子内部的并列词，最后一个尽量使用（和）来连接，使句子读起来更加连贯

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/tools/object/index.md
> +- **编辑组合**：生成一个新的组合对象后，可以在对象列表内，对组合对象进行编辑操作。编辑操作包括重命名、移动、删除、锁定、隐藏等。
中文句子内部的并列词，最后一个尽量使用（和）来连接，使句子读起来更加连贯

2022-04-25 03:43 UTC, UniqueDisplayNameIsInUse commented on zh/tools/object/video/index.md
> +- **裁剪视频** 支持通过拖动首尾滑动条以及输入需要裁剪的时间，对当前视频的长度进行裁剪操作。
使用分点 -  介绍时，建议保持统一的格式，如下文有冒号，这里没有

2022-04-25 08:11 UTC, UniqueDisplayNameIsInUse approved these changes

2022-04-25 08:12 UTC, merged